# Generated by Django 4.2.3 on 2023-07-26 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('pet_type', models.CharField(choices=[('Cat', 'Cat'), ('Dog', 'Dog'), ('Bird', 'Bird')], max_length=20)),
                ('accessory_type', models.CharField(choices=[('Accessories', 'Accessories'), ('Health & Care', 'Health & Care'), ('Food', 'Food'), ('Litter', 'Litter'), ('Beds & Carrier', 'Beds & Carrier')], max_length=100)),
                ('brand', models.CharField(max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('short_description', models.TextField()),
                ('long_description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True)),
                ('is_avialable', models.BooleanField(default=True)),
                ('is_favorite', models.BooleanField(default=False)),
            ],
        ),
    ]
