# Generated by Django 4.2.3 on 2023-07-26 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_api', '0002_alter_item_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='item_api/product_images/'),
        ),
    ]
