# Generated by Django 4.2.3 on 2023-07-29 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_api', '0003_alter_item_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.SlugField(blank=True, max_length=500, null=True, unique=True),
        ),
    ]
