# Generated by Django 4.2.3 on 2023-08-06 07:34

from django.db import migrations, models
import item_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('item_api', '0004_alter_item_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_upcoming',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to=item_api.models.product_image_upload_path),
        ),
    ]
