# Generated by Django 4.2.3 on 2023-07-29 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_api', '0003_rename_total_price_cartitem_sub_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='slug',
            field=models.SlugField(blank=True, max_length=500, null=True, unique=True),
        ),
    ]
