# Generated by Django 4.2.3 on 2023-07-29 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_api', '0005_remove_cartitem_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='product_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
