# Generated by Django 4.2.3 on 2023-07-29 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart_api', '0006_cartitem_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='product_name',
        ),
    ]
