# Generated by Django 4.2.3 on 2023-08-06 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart_api', '0009_remove_cart_product_name_cartitem_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='product_name',
        ),
    ]
